(() => {
  const DEMO_KEY='ats_v9_client_ops_demo_v2';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const stageOrder=['Onboarding','Content Preparation','Design','Development','Internal QA','Client Review','Revisions','Final Approval','Final Payment','Deployment','Completed'];
  const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const money=v=>new Intl.NumberFormat('en-US').format(Number(v||0));
  let currentClient=null,currentProject=null;

  function load(){try{return JSON.parse(localStorage.getItem(DEMO_KEY)||'{}')}catch{return {}}}
  function save(d){localStorage.setItem(DEMO_KEY,JSON.stringify(d))}
  function toast(m){const e=$('#portal-toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
  function clientProjects(d,c){return (d.projects||[]).filter(p=>p.clientId===c.id)}
  function projectPayments(d,p){const c=(d.clients||[]).find(x=>x.id===p.clientId);return (d.payments||[]).filter(x=>x.leadId===c?.leadId)}
  function publicStages(){return ['Onboarding','Design','Development','Client Review','Delivery']}
  function publicStageFor(stage){if(['Onboarding','Content Preparation'].includes(stage))return'Onboarding';if(stage==='Design')return'Design';if(['Development','Internal QA'].includes(stage))return'Development';if(['Client Review','Revisions','Final Approval','Final Payment'].includes(stage))return'Client Review';return'Delivery'}

  function init(){const d=load();currentClient=(d.clients||[])[0]||null;if(!currentClient){$('#portal-empty').classList.remove('hidden');$('#portal-app').classList.add('hidden');return}$('#portal-empty').classList.add('hidden');$('#portal-app').classList.remove('hidden');const projects=clientProjects(d,currentClient);currentProject=projects.find(p=>p.status!=='completed')||projects[0]||null;renderProfile();renderHome();renderProjects();renderPayments();renderAccount();handleHash()}
  function renderProfile(){$('#portal-title').textContent=`Welcome, ${currentClient.name.split(' ')[0]}.`;$('#portal-profile-name').textContent=currentClient.name;$('#portal-profile-company').textContent=currentClient.company||'Client';$('#portal-avatar').textContent=(currentClient.name||'C').charAt(0).toUpperCase()}

  function renderHome(){if(!currentProject)return;const d=load(),p=currentProject,idx=publicStages().indexOf(publicStageFor(p.stage));$('#home-project-title').textContent=p.title;$('#home-project-id').textContent=p.id;$('#home-progress').textContent=`${p.progress||0}%`;$('#home-progress-bar').style.width=`${p.progress||0}%`;$('#home-stage').textContent=publicStageFor(p.stage);$('#home-next-stage').textContent=idx<publicStages().length-1?`Next: ${publicStages()[idx+1]}`:'Final delivery stage';$('#home-action').textContent=p.clientAction||'No action required';const noAction=!p.clientAction||p.clientAction==='No action required';$('#home-action-copy').textContent=noAction?'Our team is currently working on your project. We’ll notify you when we need something from you.':'This is the single action currently required from you before the project can continue.';$('#home-action-button').classList.toggle('hidden',noAction);$('#home-timeline').innerHTML=publicStages().map((s,i)=>`<div class="client-stage ${i<idx?'done':i===idx?'current':''}"><span>${String(i+1).padStart(2,'0')}</span><b>${escapeHtml(s)}</b></div>`).join('');const latest=(p.updates||[])[0];$('#home-latest-update').innerHTML=latest?`<b>${escapeHtml(latest.title||'Project Update')}</b><p>${escapeHtml(latest.content)}</p><small>${escapeHtml(latest.createdAtLabel||'Recent')}</small>`:'<b>No update posted yet.</b><p>Your Studio updates will appear here as the project progresses.</p>';const pays=projectPayments(d,p),paid=pays.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount||0),0);$('#home-paid').textContent=`EGP ${money(paid)}`;$('#home-remaining').textContent=`EGP ${money(Math.max(0,Number(p.projectValue||0)-paid))}`}

  function renderProjects(){const d=load(),ps=clientProjects(d,currentClient);$('#portal-project-list').innerHTML=ps.length?ps.map(p=>`<div class="portal-project-row"><div><b>${escapeHtml(p.title)}</b><small>${escapeHtml(p.id)}</small></div><span>${escapeHtml(publicStageFor(p.stage))}</span><span><div class="mini-progress"><i style="width:${Number(p.progress||0)}%"></i></div><small>${Number(p.progress||0)}% complete</small></span><span>${escapeHtml(p.status||'active')}</span><button type="button" data-project-open="${escapeHtml(p.id)}">OPEN →</button></div>`).join(''):'<div class="portal-card">No projects yet.</div>'}

  function renderProjectDetail(id){const d=load(),p=clientProjects(d,currentClient).find(x=>x.id===id);if(!p)return;currentProject=p;const idx=publicStages().indexOf(publicStageFor(p.stage)),latest=(p.updates||[])[0];$('#client-project-detail').innerHTML=`<section class="portal-card client-project-hero"><p class="eyebrow">${escapeHtml(p.id)}</p><h2>${escapeHtml(p.title)}</h2><p>${escapeHtml(p.client)}</p><div class="client-project-meta"><div><span>STAGE</span><b>${escapeHtml(publicStageFor(p.stage))}</b></div><div><span>PROGRESS</span><b>${Number(p.progress||0)}%</b></div><div><span>DEADLINE</span><b>${escapeHtml(p.deadline||'—')}</b></div><div><span>STATUS</span><b>${escapeHtml(p.status||'active')}</b></div></div></section><div class="client-project-layout"><section class="portal-card"><div class="card-head"><div><p class="eyebrow">PROJECT TIMELINE</p><h3>Current Progress</h3></div></div><div class="client-timeline">${publicStages().map((s,i)=>`<div class="client-stage ${i<idx?'done':i===idx?'current':''}"><span>${String(i+1).padStart(2,'0')}</span><b>${escapeHtml(s)}</b></div>`).join('')}</div><div class="latest-update" style="margin-top:14px"><b>${escapeHtml(latest?.title||'No update posted yet')}</b><p>${escapeHtml(latest?.content||'Project updates from the Studio will appear here.')}</p></div></section><aside class="portal-card action-card"><p class="eyebrow">YOUR ACTION</p><h3>${escapeHtml(p.clientAction||'No action required')}</h3><p>${p.clientAction&&p.clientAction!=='No action required'?'This action is required before the project can continue.':'Nothing is required from you right now.'}</p></aside></div>`;showView('project-detail');history.replaceState(null,'',`#project/${encodeURIComponent(id)}`)}

  function renderPayments(){if(!currentProject)return;const d=load(),p=currentProject,pays=projectPayments(d,p),paid=pays.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount||0),0),remaining=Math.max(0,Number(p.projectValue||0)-paid);$('#portal-payment-summary').innerHTML=`<article class="portal-card"><span>PROJECT TOTAL</span><strong>EGP ${money(p.projectValue||0)}</strong></article><article class="portal-card"><span>PAID</span><strong>EGP ${money(paid)}</strong></article><article class="portal-card"><span>REMAINING</span><strong>EGP ${money(remaining)}</strong></article>`;$('#portal-payment-list').innerHTML=pays.length?pays.map(x=>`<div class="portal-payment-row"><div><b>${escapeHtml(x.type==='deposit'?'Project Deposit':x.type)}</b><small>${escapeHtml(x.id)}</small></div><span>EGP ${money(x.amount)}</span><span>${escapeHtml(x.status.toUpperCase())}</span><span>${escapeHtml(x.dueDate||'—')}</span><span>${x.status==='paid'?'Confirmed':'Pending'}</span></div>`).join(''):'<div class="portal-card">No payment records yet.</div>'}
  function renderAccount(){$('#portal-account').innerHTML=[['Name',currentClient.name],['Company',currentClient.company||'—'],['Email',currentClient.email||'—'],['Phone',currentClient.phone||'—'],['Client ID',currentClient.id],['Status',currentClient.status||'active']].map(([l,v])=>`<div><span>${escapeHtml(l.toUpperCase())}</span><b>${escapeHtml(v)}</b></div>`).join('')}

  function showView(v){$$('.portal-view').forEach(x=>x.classList.toggle('active',x.dataset.portalView===v));$$('[data-portal-nav]').forEach(x=>x.classList.toggle('active',x.dataset.portalNav===v));if(v==='home'){$('#portal-title').textContent=`Welcome, ${currentClient.name.split(' ')[0]}.`;$('#portal-subtitle').textContent='Everything important about your project, in one place.'}else{$('#portal-title').textContent=({'projects':'My Projects','project-detail':'Project','files':'Files','payments':'Payments','new-project':'Start New Project','account':'Account'})[v]||'Client Portal';$('#portal-subtitle').textContent='ATS · Client Portal'}window.scrollTo({top:0,behavior:'smooth'})}
  function navigate(v){if(v==='home')showView('home');else if(v==='projects')showView('projects');else if(v==='files')showView('files');else if(v==='payments'){renderPayments();showView('payments')}else if(v==='new-project')showView('new-project');else if(v==='account')showView('account');history.replaceState(null,'',`#${v}`)}
  function handleHash(){const h=location.hash.replace(/^#/,'');if(h.startsWith('project/'))return renderProjectDetail(decodeURIComponent(h.slice(8)));navigate(h||'home')}

  document.addEventListener('click',e=>{const nav=e.target.closest('[data-portal-nav]');if(nav){e.preventDefault();navigate(nav.dataset.portalNav)}const open=e.target.closest('[data-project-open],[data-open-project]');if(open){e.preventDefault();const id=open.dataset.projectOpen||currentProject?.id;if(id)renderProjectDetail(id)}});
  $('#home-action-button').addEventListener('click',()=>{if(currentProject?.clientAction?.toLowerCase().includes('pay'))navigate('payments');else toast('Approval / upload action screen is the next Client Portal slice.')});
  $('#new-project-form').addEventListener('submit',e=>{e.preventDefault();const goal=$('#new-goal').value.trim();if(!goal)return toast('Tell us the project goal first');const d=load(),num=Math.max(0,...(d.leads||[]).map(l=>Number(String(l.id||'').match(/(\d+)$/)?.[1]||0)))+1,id=`ATS-L-${String(num).padStart(4,'0')}`;d.leads=d.leads||[];d.leads.push({id,name:currentClient.name,company:currentClient.company,email:currentClient.email,phone:currentClient.phone,service:$('#new-service').value,budget:$('#new-budget').value,timeline:$('#new-timeline').value,source:'Client Portal · Returning Client',status:'new',fit:'Existing Client',createdAt:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),goal,assets:[],questions:[],notes:'',lostReason:'',existingClientId:currentClient.id,activity:[{title:'Repeat project request received',meta:`Client Portal · ${currentClient.id}`} ]});save(d);$('#new-goal').value='';toast(`${id} created · Studio notified`);setTimeout(()=>navigate('projects'),700)});
  window.addEventListener('hashchange',handleHash);
  init();
})();