(() => {
  const KEY='ats_v9_client_ops_demo_v2';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  let currentReviewId=null,currentProjectId=null;
  function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
  function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
  function toast(m){const e=$('#portal-toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
  function nextId(list,prefix){const n=Math.max(0,...list.map(x=>Number(String(x.id||'').match(/(\d+)$/)?.[1]||0)))+1;return `${prefix}${String(n).padStart(4,'0')}`}
  function ensure(){const d=load();d.projects=Array.isArray(d.projects)?d.projects:[];d.clients=Array.isArray(d.clients)?d.clients:[];d.projects.forEach(p=>{p.reviews=Array.isArray(p.reviews)?p.reviews:[];p.revisions=Array.isArray(p.revisions)?p.revisions:[];p.includedRevisions=Number.isFinite(p.includedRevisions)?p.includedRevisions:2;p.activity=Array.isArray(p.activity)?p.activity:[]});save(d);return d}
  function activeClient(d){return (d.clients||[])[0]||null}
  function activeProject(d){const c=activeClient(d);if(!c)return null;return d.projects.find(p=>p.clientId===c.id&&p.status!=='completed')||d.projects.find(p=>p.clientId===c.id)||null}
  function pendingReview(p){return (p?.reviews||[]).find(r=>r.status==='awaiting_review')||null}

  function injectView(){const files=$('[data-portal-view="files"]');if(!files||$('[data-portal-view="review"]'))return;files.insertAdjacentHTML('beforebegin',`<section class="portal-view" data-portal-view="review"><button class="back-link" type="button" data-review-back>← BACK TO PROJECT</button><div class="review-screen"><article class="review-card"><div class="card-head"><div><p class="eyebrow">CLIENT REVIEW</p><h2 id="review-title">Deliverable</h2><p id="review-project-label">Project</p></div><span class="review-status" id="review-status">AWAITING REVIEW</span></div><div class="review-preview"><div><strong id="review-preview-title">Deliverable Preview</strong><span id="review-preview-version">Version V1</span></div></div><div class="review-actions"><button class="change-button" type="button" id="request-changes">REQUEST CHANGES</button><button class="approve-button" type="button" id="approve-review">APPROVE VERSION</button></div><div class="revision-box hidden" id="revision-box"><p class="eyebrow">REVISION REQUEST</p><textarea id="revision-notes" placeholder="Please group all requested changes for this revision round in one message."></textarea><button class="portal-button" id="submit-revision" type="button">SUBMIT REVISION REQUEST →</button></div><div id="review-result"></div></article></div></section>`)}
  function showReview(){const d=ensure(),p=activeProject(d),r=pendingReview(p);if(!p||!r)return toast('No review is currently waiting for you');currentProjectId=p.id;currentReviewId=r.id;$('#review-title').textContent=`${r.title} · ${r.version}`;$('#review-project-label').textContent=`${p.title} · ${p.id}`;$('#review-preview-title').textContent=r.title;$('#review-preview-version').textContent=`Version ${r.version}`;$('#review-status').textContent='AWAITING REVIEW';$('#revision-box').classList.add('hidden');$('#review-result').innerHTML='';$$('.portal-view').forEach(v=>v.classList.toggle('active',v.dataset.portalView==='review'));$$('[data-portal-nav]').forEach(n=>n.classList.remove('active'));$('#portal-title').textContent='Review Deliverable';$('#portal-subtitle').textContent='Approve this version or request one consolidated revision round.';history.replaceState(null,'','#review')}
  function approve(){const d=ensure(),p=d.projects.find(x=>x.id===currentProjectId),r=p?.reviews.find(x=>x.id===currentReviewId);if(!p||!r)return;r.status='approved';r.approvedAt=new Date().toISOString();r.updatedLabel='Approved now';p.clientAction='No action required';p.activity.unshift({title:'Client approved review version',meta:`${r.id} · ${r.title} ${r.version}`});save(d);$('#review-status').textContent='APPROVED';$('#review-result').innerHTML='<div class="review-confirmed">Version approved successfully. The Studio has been notified and the project can continue to the next internal step.</div>';$('#approve-review').disabled=true;$('#request-changes').disabled=true;toast('Version approved · Studio notified')}
  function requestChanges(){$('#revision-box').classList.remove('hidden');$('#revision-notes').focus()}
  function submitRevision(){const notes=$('#revision-notes').value.trim();if(!notes)return toast('Add the requested changes first');const d=ensure(),p=d.projects.find(x=>x.id===currentProjectId),r=p?.reviews.find(x=>x.id===currentReviewId);if(!p||!r)return;const used=p.revisions.length;if(used>=p.includedRevisions)return toast('Included revision rounds are already used');const rv={id:nextId(p.revisions,'ATS-RV-'),reviewId:r.id,number:used+1,title:`${r.title} · ${r.version}`,notes,status:'submitted',submittedAt:new Date().toISOString()};p.revisions.push(rv);r.status='changes_requested';r.updatedLabel='Changes requested now';p.stage='Revisions';p.progress=88;p.clientAction='No action required';p.activity.unshift({title:'Client submitted revision request',meta:`Revision #${rv.number} · ${rv.id}`});save(d);$('#review-status').textContent='CHANGES REQUESTED';$('#revision-box').classList.add('hidden');$('#review-result').innerHTML=`<div class="review-confirmed">Revision #${rv.number} was submitted. No further action is required from you until the updated version is ready.</div>`;$('#approve-review').disabled=true;$('#request-changes').disabled=true;toast(`Revision #${rv.number} submitted`)}
  function backToProject(){const d=ensure(),p=activeProject(d);if(!p)return;location.hash=`#project/${encodeURIComponent(p.id)}`;location.reload()}

  injectView();
  document.addEventListener('click',e=>{const action=e.target.closest('#home-action-button');const back=e.target.closest('[data-review-back]');if(action){const d=ensure(),p=activeProject(d);if(pendingReview(p)){e.preventDefault();e.stopImmediatePropagation();showReview();return}}if(back){e.preventDefault();backToProject()}},true);
  $('#approve-review')?.addEventListener('click',approve);$('#request-changes')?.addEventListener('click',requestChanges);$('#submit-revision')?.addEventListener('click',submitRevision);
  window.addEventListener('hashchange',()=>{if(location.hash==='#review')setTimeout(showReview,0)});if(location.hash==='#review')setTimeout(showReview,50);
})();