(()=>{
  const KEY='andrew_portfolio_lang';
  const dict={
    'Home':'الرئيسية','About':'عني','Worlds':'مجالاتي','Projects':'المشاريع','Explore':'استكشف','Contact':'تواصل','Work':'الأعمال','Admin':'الإدارة',
    "Let's Talk":'تواصل معي',"Let's Talk →":'تواصل معي',"LET'S TALK →":'تواصل معي','EXPLORE MY WORK':'استكشف أعمالي','WATCH SHOWREEL':'شاهد العرض','Years Experience':'سنوات خبرة','Projects Delivered':'مشروع تم تنفيذه','Creative Worlds':'مجالات إبداعية','Purpose: Real Impact':'هدف واحد: أثر حقيقي',
    'SAFETY ENGINEER • DIGITAL CREATOR • VISUAL ARTIST • AI EXPLORER':'مهندس سلامة • صانع حلول رقمية • فنان بصري • مبدع بالذكاء الاصطناعي',
    'HSE PROFESSIONAL • DIGITAL CREATOR • VISUAL ARTIST • AI CREATIVE':'متخصص HSE • صانع حلول رقمية • فنان بصري • مبدع بالذكاء الاصطناعي',
    'I TURN IDEAS INTO':'أحوّل الأفكار إلى','SYSTEMS, STORIES &':'أنظمة وقصص','VISUAL EXPERIENCES.':'وتجارب بصرية',
    'From safer workplaces and digital systems to brands, stories and AI-powered visual experiences — I build ideas that solve real problems and create a brighter tomorrow.':'من بيئات عمل أكثر أمانًا وأنظمة رقمية إلى الهويات والقصص والتجارب المدعومة بالذكاء الاصطناعي — أحوّل الأفكار إلى حلول حقيقية تصنع أثرًا أفضل.',
    'From safer workplaces and digital systems to brands, stories and AI-powered visual experiences — I build ideas that solve real problems.':'من بيئات عمل أكثر أمانًا وأنظمة رقمية إلى الهويات والقصص والتجارب المدعومة بالذكاء الاصطناعي — أحوّل الأفكار إلى حلول حقيقية لمشكلات واقعية.',
    'SAFETY':'السلامة','CREATIVITY':'الإبداع','TECHNOLOGY':'التكنولوجيا','PEOPLE':'الناس','A BRIGHTER':'مستقبل','TOMORROW':'أفضل',
    'WHO I AM':'من أنا','ONE MIND.':'عقل واحد','MANY WAYS TO CREATE.':'ومساحات كثيرة للإبداع','What looks like different fields to others is one process to me: understanding a problem, creating an idea, and turning it into something real.':'ما يبدو للآخرين مجالات مختلفة هو بالنسبة لي مسار واحد: أفهم المشكلة، أصنع الفكرة، ثم أحولها إلى شيء حقيقي.',
    'People':'الناس','Environments':'بيئات العمل','Real Impact':'أثر حقيقي','Digital Solutions':'حلول رقمية','Automation':'أتمتة','Data':'بيانات','DESIGN':'التصميم','Visual Ideas':'أفكار بصرية','Brands':'هويات','Creative Concepts':'مفاهيم إبداعية','STORIES':'القصص','Ideas':'أفكار','Characters':'شخصيات','Meaningful Content':'محتوى له معنى','AI':'الذكاء الاصطناعي','Bigger Possibilities':'إمكانات أكبر','Faster Creation':'تنفيذ أسرع','Real Solutions':'حلول حقيقية',
    'MY WORLDS':'مجالاتي','IDEAS IN':'الأفكار تتحول إلى','ACTION.':'واقع','Real-world experience. Creative thinking. Tangible impact.':'خبرة حقيقية، تفكير إبداعي، وأثر ملموس.',
    'HOW I THINK':'طريقتي في التفكير',"I DON'T JUST DESIGN.":'أنا لا أصمم فقط','I BUILD SOLUTIONS.':'أنا أبني حلولًا','Different challenges. One approach. Real results.':'تحديات مختلفة، منهج واحد، ونتائج حقيقية.',
    'A Safety Problem':'مشكلة سلامة','→ Digital HSE Tool':'أداة HSE رقمية','A Message':'رسالة','→ Awareness Film':'فيلم توعوي','An Idea':'فكرة','→ Brand Identity':'هوية بصرية',"A Child's Photo":'صورة طفل','→ Personalized Story':'قصة مخصصة','Raw Data':'بيانات خام','→ Actionable Dashboard':'لوحة بيانات قابلة للتنفيذ','A Concept':'تصور','→ Website':'موقع إلكتروني',
    'FEATURED WORK':'أعمال مختارة','REAL PROJECTS.':'مشاريع حقيقية','REAL IMPACT.':'أثر حقيقي','A selection of projects that reflect different sides of my journey.':'مجموعة مختارة من المشاريع التي تعكس جوانب مختلفة من رحلتي.','VIEW ALL PROJECTS':'عرض كل المشاريع','VIEW PROJECT →':'عرض المشروع',
    'EXPLORE MORE':'استكشف أكثر','DEEPER INTO THE':'تعمّق أكثر في','BRAND WORLD.':'عالم الهوية','Extracted visual sections from the approved art direction — now integrated into the website experience.':'مساحات بصرية من الهوية المعتمدة أصبحت جزءًا من تجربة الموقع.',
    'MY APPROACH':'منهجي','THINK. CREATE. BUILD.':'فكّر. ابتكر. نفّذ.','IMPROVE.':'طوّر','THINK.':'فكّر','CREATE.':'ابتكر','BUILD.':'نفّذ','Understand the problem and context before execution.':'افهم المشكلة والسياق قبل التنفيذ.','Turn ideas into concepts, visuals and experiences.':'حوّل الأفكار إلى مفاهيم وصور وتجارب.','Make the idea tangible, useful and testable.':'حوّل الفكرة إلى شيء ملموس ومفيد وقابل للاختبار.','Refine the result until it becomes stronger and smarter.':'طوّر النتيجة حتى تصبح أقوى وأذكى.',
    'SAFER IDEAS':'أفكار أكثر أمانًا','GOT AN IDEA?':'عندك فكرة؟',"LET'S MAKE IT REAL.":'خلينا نحولها لحقيقة','New project, collaboration or just want to say hello? I’d love to hear from you.':'مشروع جديد، تعاون، أو حتى مجرد فكرة؟ يسعدني تواصلك معي.','New project, collaboration or just want to say hello? I\'d love to hear from you.':'مشروع جديد، تعاون، أو حتى مجرد فكرة؟ يسعدني تواصلك معي.','Start a Project':'ابدأ مشروعك','All rights reserved.':'جميع الحقوق محفوظة.',
    'SAFETY × CREATIVITY × TECHNOLOGY × PEOPLE':'سلامة × إبداع × تكنولوجيا × إنسان','SAFER IDEAS.':'أفكار أكثر أمانًا','REAL IMPACT.':'أثر حقيقي',
    'EXPERIENCE MY WORK':'استكشف أعمالي','REAL PROBLEMS.':'تحديات حقيقية','REAL OUTPUTS.':'نتائج ملموسة','This is where the different sides of my work meet: field HSE experience, digital systems, design, storytelling and AI. Every project below is based on work I have actually built, developed or actively use.':'هنا تلتقي جوانب عملي المختلفة: خبرة HSE الميدانية، الأنظمة الرقمية، التصميم، السرد والذكاء الاصطناعي. كل مشروع هنا مبني على عمل قمت بتنفيذه أو تطويره أو أستخدمه فعليًا.',
    'HSE FIELD EXPERIENCE':'خبرة HSE ميدانية','Construction, port activities, inspections, risk assessment and corrective-action follow-up.':'إنشاءات، أعمال موانئ، تفتيش، تقييم مخاطر ومتابعة الإجراءات التصحيحية.','DIGITALIZATION':'التحول الرقمي','Data organization, reporting, dashboards, automation and practical web tools.':'تنظيم البيانات، التقارير، لوحات المتابعة، الأتمتة وأدوات الويب العملية.','VISUAL CREATION':'الإبداع البصري','Brand systems, graphic design, art direction and communication assets.':'أنظمة الهوية، التصميم الجرافيكي، الإخراج الفني وأصول الاتصال البصري.','AI & STORYTELLING':'الذكاء الاصطناعي والسرد','Awareness films, personalized stories, visual concepts and AI-assisted products.':'أفلام توعوية، قصص مخصصة، مفاهيم بصرية ومنتجات مدعومة بالذكاء الاصطناعي.','All Work':'كل الأعمال','Loading work…':'جاري تحميل الأعمال…','Loading real project data…':'جاري تحميل بيانات المشاريع…','OPEN CASE STUDY':'عرض دراسة الحالة','OPEN CASE STUDY →':'عرض دراسة الحالة','COMING SOON':'قريبًا','No published projects in this category yet.':'لا توجد مشاريع منشورة في هذا القسم حاليًا.','Could not load the live project data right now.':'تعذر تحميل بيانات المشاريع حاليًا.','WORK DATA UNAVAILABLE':'بيانات الأعمال غير متاحة حاليًا',
    'SEEN SOMETHING THAT SPARKED AN IDEA?':'شفت حاجة ولّدت عندك فكرة؟',"DON'T JUST BROWSE.":'ما تكتفيش بالمشاهدة.','BUILD YOURS.':'خلينا نبني فكرتك.','If one of the projects gave you an idea, contact me directly. A rough idea is enough to start.':'لو مشروع من الأعمال ألهمك بفكرة، تواصل معي مباشرة. حتى لو الفكرة لسه أولية نقدر نبدأ منها.','WHATSAPP →':'واتساب','EMAIL BRIEF →':'إرسال الفكرة بالبريد','WA · START IDEA':'واتساب · ابدأ فكرتك','@ · EMAIL':'البريد الإلكتروني',
    "LET'S BUILD SOMETHING REAL":'خلينا نبني حاجة حقيقية','HAVE A PROJECT?':'عندك مشروع؟','OR JUST AN IDEA?':'أو حتى مجرد فكرة؟',"Whether it's HSE, a website, brand, awareness video, AI experience, story or something new — tell me what you want to build.":'سواء HSE، موقع، هوية، فيديو توعوي، تجربة ذكاء اصطناعي، قصة أو فكرة جديدة — احكي لي ماذا تريد أن نبني.','START ON WHATSAPP':'ابدأ على واتساب','SEND PROJECT BY EMAIL':'أرسل المشروع بالبريد','Professional profile & HSE work':'الملف المهني وأعمال HSE','Personal creative profile':'الحساب الشخصي والإبداعي','Personalized stories':'قصص مخصصة','Smart document solutions':'حلول مستندات ذكية','Direct contact':'تواصل مباشر','No formal brief is required. Explain the idea in your own words and we can build from there.':'لا تحتاج لملف رسمي. اشرح فكرتك بطريقتك، ونبدأ من هناك.','WhatsApp':'واتساب','Email':'البريد الإلكتروني',
    'My work moves across safety, digital systems, visual design, storytelling and AI — but every project starts the same way: understand the problem, build something useful, and improve the experience.':'أعمالي تمتد بين السلامة والأنظمة الرقمية والتصميم البصري والقصص والذكاء الاصطناعي، لكن كل مشروع يبدأ بالطريقة نفسها: فهم المشكلة، بناء حل مفيد، ثم تحسين التجربة.','Published Projects':'مشاريع منشورة','Connected Journey':'رحلة مترابطة','ALL WORK':'كل الأعمال','Search projects, tools or tags...':'ابحث في المشاريع أو الأدوات أو الكلمات المفتاحية...','Loading projects…':'جاري تحميل المشاريع…','NEXT IDEA':'فكرتك التالية','SEEN SOMETHING':'شفت حاجة لفتت انتباهك؟','YOU WANT TO BUILD?':'حابب نبني حاجة مشابهة؟',"Whether it's an HSE system, awareness film, website, visual identity or a new AI-powered idea — let's turn it into something real.":'سواء كان نظام HSE، فيلمًا توعويًا، موقعًا، هوية بصرية أو فكرة جديدة بالذكاء الاصطناعي — خلينا نحولها إلى شيء حقيقي.','START A PROJECT →':'ابدأ مشروعك',
    'BACK TO WORK':'العودة للأعمال','← BACK TO WORK':'العودة للأعمال','← BACK TO SELECTED WORK':'العودة إلى الأعمال المختارة','BACK TO SELECTED WORK ←':'العودة إلى الأعمال المختارة','PROBLEM SOLVING THROUGH CREATIVITY':'حل المشكلات من خلال الإبداع','CASE STUDY':'دراسة حالة','THE PROJECT.':'المشروع','01 / CHALLENGE':'01 / التحدي','THE CHALLENGE.':'التحدي','02 / SOLUTION':'02 / الحل','THE SOLUTION.':'الحل','03 / RESULT':'03 / النتيجة','THE IMPACT.':'الأثر','PROJECT GALLERY.':'معرض المشروع','VISUAL ARCHIVE':'الأرشيف البصري','Images and video from the project.':'صور وفيديوهات من المشروع.','VIEW LIVE →':'عرض المشروع','WATCH VIDEO →':'شاهد الفيديو','GITHUB →':'GitHub','HANDCRAFTED COLLECTION':'مجموعة يدوية','SELECTED ARTWORKS.':'أعمال مختارة','SWIPE / DRAG • OR USE ARROWS':'اسحب للمشاهدة • أو استخدم الأسهم','PROCESS / MOTION':'عملية التنفيذ','HANDCRAFTED PORTRAIT':'بورتريه مصنوع يدويًا','ORDER YOUR PORTRAIT':'اطلب بورتريه خاص بك','ARTWORK':'عمل فني','VIDEO':'فيديو','VIEW':'عرض',
    'Project page is not available yet':'صفحة المشروع غير متاحة حاليًا','This project is either not published yet or its public page is currently disabled.':'هذا المشروع إما غير منشور بعد أو أن صفحته العامة غير مفعلة.','Could not load projects.':'تعذر تحميل المشاريع.','Please try again shortly.':'حاول مرة أخرى بعد قليل.','No projects match this filter yet.':'لا توجد مشاريع مطابقة لهذا الفلتر حاليًا.','VIEW CASE STUDY →':'عرض تفاصيل المشروع','Project':'مشروع','Creative':'إبداع وتصميم','Digital':'حلول رقمية','Safety':'السلامة والصحة المهنية','Stories & AI':'القصص والذكاء الاصطناعي',
    'Loading project...':'جاري تحميل المشروع...','Configuration error':'خطأ في الإعدادات','Project not found':'المشروع غير موجود','CLICK OUTSIDE OR PRESS ESC TO CLOSE':'اضغط خارج الصورة أو ESC للإغلاق','Open menu':'فتح القائمة','Main navigation':'القائمة الرئيسية','Social links':'روابط التواصل','Previous artwork':'العمل السابق','Next artwork':'العمل التالي'
  };

  const visualLabels={
    'Safety world card':'السلامة والصحة المهنية','Digital world card':'الحلول الرقمية','Creative world card':'الإبداع والتصميم','Stories and AI world card':'القصص والذكاء الاصطناعي',
    'Safety focus section':'السلامة والصحة المهنية','Digital focus section':'الحلول الرقمية','Creative focus section':'الإبداع والتصميم','AI focus section':'القصص والذكاء الاصطناعي',
    'HSE awareness series':'سلسلة التوعية بالسلامة','HSE digital tools':'أدوات HSE الرقمية','DO personalized stories':'قصص DO المخصصة','Magic of string art':'Magic of String Art','Brand identity projects':'مشاريع الهوية البصرية'
  };

  const originals=new WeakMap();
  const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
  const current=()=>localStorage.getItem(KEY)==='ar'?'ar':'en';
  function translateText(text){const n=norm(text);if(!n)return text;if(dict[n])return text.replace(n,dict[n]);const m=n.match(/^(\d+) projects? shown$/i);if(m)return `${m[1]} مشروع ظاهر`;const x=n.match(/^(\d+) PROJECTS? • LIVE WORK DATA$/i);if(x)return `${x[1]} مشروع • بيانات مباشرة`;return text}
  function shouldSkip(parent){return !parent||['SCRIPT','STYLE','NOSCRIPT','TEXTAREA','INPUT'].includes(parent.tagName)||!!parent.closest('[data-i18n-skip]')}
  function applyNode(node,lang){if(node.nodeType!==Node.TEXT_NODE)return;const parent=node.parentElement;if(shouldSkip(parent))return;if(!originals.has(node))originals.set(node,node.nodeValue);const base=originals.get(node);node.nodeValue=lang==='ar'?translateText(base):base;}
  function applyAttrs(root,lang){root.querySelectorAll?.('[placeholder],[title],[aria-label]').forEach(el=>{['placeholder','title','aria-label'].forEach(a=>{if(!el.hasAttribute(a))return;const key='i18nOriginal'+a.replace(/(^|-)([a-z])/g,(_,dash,ch)=>ch.toUpperCase());if(!el.dataset[key])el.dataset[key]=el.getAttribute(a)||'';const base=el.dataset[key];el.setAttribute(a,lang==='ar'?(dict[base]||base):base)})});}
  function walk(root=document.body,lang=current()){if(!root)return;if(root.nodeType===Node.TEXT_NODE)applyNode(root,lang);if(root.nodeType===Node.ELEMENT_NODE&&root.matches?.('[data-i18n-skip]'))return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode()))applyNode(n,lang);applyAttrs(root,lang);}
  function injectVisualLabels(){document.querySelectorAll('.image-card img,.wide-image-card img').forEach(img=>{const label=visualLabels[img.alt];if(!label)return;const card=img.closest('.image-card,.wide-image-card');if(!card||card.querySelector('.i18n-visual-label'))return;const s=document.createElement('span');s.className='i18n-visual-label';s.textContent=label;s.setAttribute('aria-hidden','true');card.appendChild(s);});}
  function updateButtons(lang){document.querySelectorAll('.lang-toggle').forEach(b=>{b.textContent=lang==='ar'?'EN':'عربي';b.setAttribute('aria-label',lang==='ar'?'Switch to English':'التبديل إلى العربية');b.title=lang==='ar'?'English':'العربية'})}
  function apply(lang){localStorage.setItem(KEY,lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body?.classList.toggle('lang-ar',lang==='ar');injectVisualLabels();walk(document.body,lang);updateButtons(lang);document.dispatchEvent(new CustomEvent('portfolio:languagechange',{detail:{lang}}));}
  function inject(){if(document.querySelector('.lang-toggle'))return;const header=document.querySelector('.site-header,.work-nav,.project-nav');if(!header)return;const b=document.createElement('button');b.type='button';b.className='lang-toggle';b.addEventListener('click',()=>apply(current()==='ar'?'en':'ar'));const cta=header.querySelector('.header-cta,.btn.btn-primary.small,.btn.btn-ghost.small');if(cta)header.insertBefore(b,cta);else header.appendChild(b);updateButtons(current());}
  const start=()=>{inject();injectVisualLabels();apply(current());const obs=new MutationObserver(ms=>{let changed=false;for(const m of ms){for(const n of m.addedNodes){if(n.nodeType===1||n.nodeType===3){walk(n,current());changed=true}}}if(changed){injectVisualLabels();updateButtons(current())}});obs.observe(document.body,{childList:true,subtree:true});};
  document.addEventListener('portfolio:contentrendered',()=>{walk(document.body,current());updateButtons(current());});
  window.PORTFOLIO_I18N={getLang:current,setLang:apply,t:(en,ar)=>current()==='ar'?(ar||dict[en]||en):en,refresh:()=>{walk(document.body,current());updateButtons(current())}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();