const {test}=require('node:test');
const assert=require('node:assert/strict');
const {createHandler}=require('../server/move-now.cjs');
const {emptyCRM,view,cleanCRM}=require('../server/move-now-call-model.cjs');
const {staffLead}=require('../server/move-now-calls.cjs');
const id='da786932-7d8b-41de-b487-e485531d12b9';
const crm=()=>({...emptyCRM(),clientName:'عميل اختبار',phone:'+12025550144',route:'buy',service:'buy_installments',financialClass:'installments',location:'زايد',downPayment:'500000',monthlyInstallment:'15000'});
const response=data=>new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});
async function run(resource,body,fetchImpl,analyzeImpl){
 const prior=process.env.SUPABASE_SECRET_KEY;process.env.SUPABASE_SECRET_KEY='test-secret';let result;
 try{await createHandler({fetchImpl:async(url,init)=>url.includes('/auth/v1/user')?response({id:'test-owner',email:'atstudioimpact@gmail.com',email_confirmed_at:'yes'}):fetchImpl(url,init),analyzeImpl})({method:'POST',query:{resource},body,headers:{host:'atstudioimpact.com',origin:'https://atstudioimpact.com',authorization:'Bearer test-user'}},{setHeader(){},status(status){return {json(data){result={status,data}}}}});return result;}
 finally{if(prior===undefined)delete process.env.SUPABASE_SECRET_KEY;else process.env.SUPABASE_SECRET_KEY=prior;}
}
test('Call compass: installment financing needs both down payment and monthly amount',()=>{const c=crm();assert.equal(view(c).compass[2].status,'complete');c.monthlyInstallment='';assert.equal(view(c).compass[2].status,'partial');});
test('Uncertain information is excluded from completion and closing promises',()=>{const c={...crm(),followupTime:'بكرة 6',whatsappConfirmed:'yes',nextStep:'معاينة'};const out=view(c,['downPayment','followupTime','whatsappConfirmed']);assert.equal(out.compass[2].status,'partial');assert.equal(out.compass[4].status,'partial');assert.ok(!out.recap.includes('500000'));assert.ok(!out.recap.includes('بكرة 6'));assert.ok(out.recap.includes('نأكد'));});
test('CRM accepts only the enumerated fields and choices',()=>{assert.throws(()=>cleanCRM({...crm(),role:'owner'}));assert.throws(()=>cleanCRM({...crm(),service:'invented'}));assert.throws(()=>cleanCRM({...crm(),budget:123}));});
test('Recap uses the same confirmed property, delivery and follow-up fields as CRM',()=>{const c={...crm(),title:'م/',propertyType:'شقة',rooms:'3',delivery:'تحت الإنشاء خلال سنة',nextStep:'إرسال دراسة العائد المجانية',followupTime:'بكرة الساعة 6 مساء',whatsappConfirmed:'yes'};const out=view(c);for(const value of [c.propertyType,c.delivery,c.nextStep,c.followupTime])assert.ok(out.recap.includes(value));assert.equal(out.compass[3].status,'complete');assert.equal(out.compass[4].status,'complete');assert.ok(!view(c,['delivery']).recap.includes(c.delivery));assert.throws(()=>cleanCRM({...c,title:'مهندس أحمد'}));});
test('Publish validates contact and service financing',()=>{assert.throws(()=>staffLead({...crm(),phone:'bad'},id,'agent@test.example',''));assert.throws(()=>staffLead({...crm(),monthlyInstallment:''},id,'agent@test.example',''));const out=staffLead(crm(),id,'agent@test.example','ملخص');assert.equal(out.phone,'+12025550144');assert.equal(JSON.parse(out.details).financialClass,'تسهيلات وتقسيط');});
test('Copilot creates a pending generation before AI and persists tokens and result',async()=>{const events=[];const result=await run('copilot',{callId:id,notes:'مقدم نص مليون',previous:emptyCRM(),locked:[]},async(url,init)=>{if(url.includes('move_now_ai_attempt'))return response(true);if(!init.method||init.method==='GET')return response([]);const body=JSON.parse(init.body);events.push(body.state);return response(null);},async(input)=>{assert.equal(events[0],'pending');assert.equal(input.notes,'مقدم نص مليون');return {crm:crm(),uncertain:[],nudge:'سؤال واحد',recap:'دراسة مجانية',usage:{inputTokens:10,outputTokens:20}};});assert.equal(result.status,200);assert.deepEqual(events,['pending','complete']);assert.ok(result.data.id);assert.equal(result.data.crm.downPayment,'500000');});
test('Copilot cached generations do not call the model again',async()=>{const result=await run('copilot',{callId:id,notes:'زايد',previous:emptyCRM(),locked:[]},async()=>response([{id,result:{crm:crm(),uncertain:[],nudge:'التالي',recap:'ملخص'}}]),async()=>{throw Error('must not run')});assert.equal(result.status,200);assert.equal(result.data.id,id);});
test('Rate limits stop AI without creating a pending run',async()=>{let writes=0;const result=await run('copilot',{callId:id,notes:'زايد',previous:emptyCRM(),locked:[]},async(url,init)=>{if(url.includes('move_now_ai_attempt'))return response(false);if(init.method&&init.method!=='GET')writes++;return response([]);},async()=>{throw Error('must not run')});assert.equal(result.status,429);assert.equal(writes,0);});
test('Call actor comes from verified identity and manual locks are stored',async()=>{let payload;const result=await run('calls',{id,notes:'اختبار',crm:crm(),uncertain:[],locked:['location'],agent_email:'forged@test.example',publish:true,updatedAt:0},async(url,init)=>{assert.ok(url.includes('rpc/move_now_save_call'));payload=JSON.parse(init.body);return response({...payload.p_record,stage:'completed'});});assert.equal(result.status,200);assert.equal(payload.p_record.agent_email,'atstudioimpact@gmail.com');assert.deepEqual(payload.p_record.analysis.locked,['location']);assert.equal(payload.p_publish,true);});
test('Unconfirmed critical fields cannot be published',async()=>{const result=await run('calls',{id,notes:'اختبار',crm:crm(),uncertain:['downPayment'],publish:true,updatedAt:0},async()=>{throw Error('must not write')});assert.equal(result.status,400);});
test('Anonymous callers cannot use CRM calls or AI endpoints',async()=>{const prior=process.env.SUPABASE_SECRET_KEY;process.env.SUPABASE_SECRET_KEY='test-secret';try{for(const resource of ['calls','copilot']){let result;await createHandler({fetchImpl:async()=>{throw Error('must not access data')}})({method:'GET',query:{resource},headers:{host:'atstudioimpact.com'}},{setHeader(){},status(status){return {json(){result=status}}}});assert.equal(result,401);}}finally{if(prior===undefined)delete process.env.SUPABASE_SECRET_KEY;else process.env.SUPABASE_SECRET_KEY=prior;}});
