// Run with: ATS_PGLITE_MODULE=/absolute/path/to/@electric-sql/pglite/dist/index.js node tests/team-engine.test.mjs
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {PGlite}=await import(process.env.ATS_PGLITE_MODULE||'@electric-sql/pglite');
const db=new PGlite();
await db.exec(readFileSync(new URL('./fixtures/team-bootstrap.sql',import.meta.url),'utf8'));
await db.exec(readFileSync(new URL('../supabase/migrations/20260927071736_ats_team_task_engine_v1.sql',import.meta.url),'utf8'));
let count=0;
const ok=(v,m)=>{assert.ok(v,m);count++;console.log('PASS',m);};
const identity=async(admin=false,uid='')=>{await db.exec(`reset role;select set_config('test.admin','${admin}',false),set_config('request.uid','${uid}',false);set role ${uid?'authenticated':'anon'};`);};
const cmd=async(a,p={})=>(await db.query('select public.studio_team_command($1,$2::jsonb) as result',[a,JSON.stringify(p)])).rows[0].result;
const fails=async(fn,message)=>{await assert.rejects(fn);count++;console.log('PASS',message);};
const read=async(table)=>(await db.query(`select * from public.${table}`)).rows;
const makerUid='20000000-0000-0000-0000-000000000001',reviewerUid='20000000-0000-0000-0000-000000000002',clientUid='20000000-0000-0000-0000-000000000003';
await identity();
await fails(()=>cmd('save_member',{}),'Anonymous caller cannot manage members');
ok((await read('studio_project_tasks')).length===0,'Anonymous reads deny all');
await identity(true);
const memberPayload={full_name:'Maker',email:'maker@test.invalid',capacity:2,skills:[{skill:'design',level:3}]};
const maker=(await cmd('save_member',memberPayload)).id;
const reviewer=(await cmd('save_member',{full_name:'Reviewer',email:'reviewer@test.invalid',skills:[{skill:'design',level:5}]})).id;
const taskPayload={project_id:'10000000-0000-0000-0000-000000000001',workstream:'Creative',title:'Poster',required_skill:'design',required_level:2,expected_output:'Print ready poster',acceptance_criteria:'Approved dimensions and content',reviewer_id:reviewer,due_at:'2026-10-01T12:00:00Z',base_tokens:25};
const a=(await cmd('create_task',taskPayload)).id;
const b=(await cmd('create_task',{...taskPayload,title:'Second'})).id;
const c=(await cmd('create_task',{...taskPayload,title:'Third'})).id;
const dependent=(await cmd('create_task',{...taskPayload,title:'Dependent',dependencies:[a]})).id;
const other=(await cmd('create_task',{...taskPayload,title:'Code',required_skill:'development'})).id;
await fails(()=>cmd('edit_task',{...taskPayload,id:a,reason:'cycle',dependencies:[dependent]}),'Reject dependency cycles');
await fails(()=>cmd('assign',{id:a,member_id:reviewer}),'No self-review assignments');
await identity(false,makerUid);
ok((await cmd('activate')).member_id===maker,'Verified email links approved member');
ok((await read('studio_project_tasks')).length===3,'RLS filters skills, dependencies and eligible marketplace');
await fails(()=>cmd('save_member',{...memberPayload,capacity:50}),'Member cannot raise capacity');
await fails(()=>cmd('claim',{id:other}),'Cannot claim unmatched skill');
await fails(()=>cmd('claim',{id:dependent}),'Cannot claim blocked dependency');
await fails(()=>db.query("update public.studio_project_tasks set status='accepted' where id=$1",[a]),'Direct task mutation denied');
await cmd('claim',{id:a});
await fails(()=>cmd('claim',{id:a}),'Repeated claim cannot duplicate reservation');
await cmd('claim',{id:b});
await fails(()=>cmd('claim',{id:c}),'Server capacity blocks third active task');
ok((await read('studio_project_tasks')).length===2,'Available work disappears at full capacity');
await cmd('start',{id:a});
await fails(()=>cmd('submit',{id:a,submission:''}),'Submission requires delivery evidence');
await cmd('submit',{id:a,submission:'https://example.com/delivery'});
await fails(()=>cmd('accept',{id:a}),'Owner cannot accept own output');
await identity(false,reviewerUid);await cmd('activate');
await fails(()=>cmd('accept',{id:a}),'Configured admin acceptance cannot be bypassed by reviewer');
await cmd('rework',{id:a,category:'contributor_error',reason:'Correct dimensions'});
ok((await read('studio_token_ledger')).length===0,'Reviewer cannot read maker wallet');
await identity(false,makerUid);
let ledger=await read('studio_token_ledger');ok(ledger.length===2&&ledger.every(x=>x.event_type==='RESERVED'),'Rework awards no tokens');
await cmd('submit',{id:a,submission:'Corrected delivery'});
await identity(true);await cmd('accept',{id:a});
await fails(()=>cmd('accept',{id:a}),'Repeated acceptance rejected');
ledger=await read('studio_token_ledger');ok(ledger.filter(x=>x.event_type==='EARNED').length===1,'One earned entry per accepted task');
await fails(()=>cmd('edit_task',{...taskPayload,id:a,reason:'Change earned tokens',base_tokens:500}),'Accepted task scope immutable');
const duplicate=(await cmd('create_task',{...taskPayload,id:a,title:'New task'})).id;
ok(duplicate!==a,'Create with existing ID cannot overwrite accepted task');
await cmd('bonus',{id:a,tokens:5,reason:'Extra deliverable',request_id:'30000000-0000-0000-0000-000000000001'});
await fails(()=>cmd('bonus',{id:a,tokens:5,reason:'Repeat',request_id:'30000000-0000-0000-0000-000000000001'}),'Bonus request is unique');
await cmd('unassign',{id:b,reason:'Replan'});
await identity(false,makerUid);await cmd('claim',{id:dependent});
ledger=await read('studio_token_ledger');
ok(ledger.reduce((s,e)=>s+(e.event_type==='RESERVED'?e.tokens:e.event_type==='RELEASED'?-e.tokens:0),0)===25,'Wallet reservation reconciles after acceptance/unassign/new claim');
ok(ledger.filter(x=>['EARNED','BONUS'].includes(x.event_type)).reduce((s,e)=>s+e.tokens,0)===30,'Wallet earned includes one acceptance plus bonus');
await fails(()=>cmd('bonus',{id:a,tokens:99,reason:'Member bonus',request_id:crypto.randomUUID()}),'Members cannot award bonuses');
await identity(false,clientUid);
await fails(()=>cmd('activate'),'Client without membership cannot activate');
for(const table of ['studio_team_members','studio_member_skills','studio_project_workstreams','studio_project_tasks','studio_token_ledger','studio_task_events'])ok((await read(table)).length===0,`Client cannot read ${table}`);
await identity(true);await cmd('save_member',{...memberPayload,id:maker,active:false});
await identity(false,makerUid);ok((await read('studio_token_ledger')).length===0,'Revocation immediately blocks wallet reads');
await fails(()=>cmd('start',{id:dependent}),'Revoked membership cannot execute tasks');
await identity(true);await cmd('save_member',{...memberPayload,id:maker,capacity:1});
await fails(()=>cmd('assign',{id:b,member_id:maker}),'Admin assignment also enforces capacity');
await cmd('assign',{id:b,member_id:maker,override_capacity:true,reason:'Approved short overlap'});
ok((await read('studio_task_events')).some(e=>e.action==='assign'&&e.details.override_capacity),'Capacity override audited');
await db.exec('reset role');
await fails(()=>db.query("delete from public.studio_token_ledger where task_id=$1",[a]),'Ledger immutable even for privileged accidental deletes');
await fails(()=>db.query("update public.studio_task_events set action='hidden' where task_id=$1",[a]),'Audit history immutable');
console.log(`\n${count} integration assertions passed against PostgreSQL (PGlite).`);
await db.close();
