const {createHash}=require('node:crypto');
const CONFIG=require('../config.js');
const services=['buy','finish','rent','both'];const statuses=['new','contacted','visit','offer','active','done','closed'];
const detailKeys=['location','type','area','rooms','bathrooms','condition','budget','purpose','timeline','style','works','furnished','rentType','brief','contactTime'];
const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
class ClientError extends Error{constructor(message,status=400){super(message);this.status=status;}}
function validateLead(body){if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!['id','name','phone','service','details','consent','website'].includes(k)))throw new ClientError('راجع بيانات الطلب.');
 const {id,service,details:d,consent,website}=body;const name=typeof body.name==='string'?body.name.trim():'';let phone=typeof body.phone==='string'?body.phone.trim():'';
 if(!uuid(id)||name.length<2||name.length>100||phone.length>25||!services.includes(service)||consent!==true||website||!d||typeof d!=='object'||Array.isArray(d))throw new ClientError('راجع البيانات المطلوبة وحاول مرة أخرى.');
 if(Object.entries(d).some(([k,v])=>!detailKeys.includes(k)||typeof v!=='string'||v.trim().length>1500))throw new ClientError('راجع تفاصيل العقار.');const details=Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v.trim()]));
 if(!details.location||!details.type||!details.timeline||!details.contactTime)throw new ClientError('كمّل المنطقة ونوع العقار والوقت المناسب.');
 if(service==='buy'&&(!details.budget||!details.purpose))throw new ClientError('كمّل الميزانية والغرض من الشراء.');
 if(service!=='buy'&&(!details.area||!details.condition))throw new ClientError('كمّل مساحة العقار وحالته.');
 for(const k of ['area','rooms','bathrooms'])if(details[k]&&(!/^\d+(\.\d+)?$/.test(details[k])||Number(details[k])<=0||Number(details[k])>(k==='area'?100000:100)))throw new ClientError('راجع المساحة وعدد الغرف والحمامات.');
 phone=phone.replace(/[\s()\-]/g,'').replace(/^00/,'+');if(/^01[0125]\d{8}$/.test(phone))phone='+20'+phone.slice(1);if(/^20\d{10}$/.test(phone))phone='+'+phone;if(!/^\+[1-9]\d{7,14}$/.test(phone))throw new ClientError('اكتب رقم واتساب صحيح مع كود الدولة.');
 const now=Date.now();return {id,name,phone,service,details:JSON.stringify(details),status:'new',assigned:'',notes:'',next_followup:'',created_at:now,updated_at:now};}
function bodyOf(req,max){const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});if(Buffer.byteLength(raw)>max)throw new ClientError('الطلب أكبر من المسموح.',413);try{return JSON.parse(raw)}catch{throw new ClientError('بيانات غير صحيحة.')}}
function requireOrigin(req){const origin=req.headers.origin;const expected=process.env.SITE_URL||'https://'+req.headers.host;if(!origin||origin!==expected.replace(/\/$/,''))throw new ClientError('غير مصرح. افتح الصفحة وحاول مرة أخرى.',403);}
function queryValue(req,name){const direct=req.query?.[name];if(Array.isArray(direct))return direct[0]||'';if(direct!==undefined&&direct!==null)return direct;try{return new URL(req.url||'','https://internal.invalid').searchParams.get(name)||'';}catch{return '';}}
function createHandler({fetchImpl=globalThis.fetch}={}){return async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');const owner=(process.env.MOVE_NOW_OWNER_EMAIL||'atstudioimpact@gmail.com').trim().toLowerCase();const url=process.env.SUPABASE_URL||CONFIG.supabaseUrl;const secret=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;const publicKey=process.env.SUPABASE_ANON_KEY||CONFIG.supabaseKey;
 const reply=(status,data)=>res.status(status).json(data);
 try{if(!secret)throw new ClientError('الخدمة غير متاحة حاليًا. حاول بعد قليل.',503);const resource=String(queryValue(req,'resource'));const method=req.method||'GET';if(!['leads','admins','session'].includes(resource))return reply(404,{error:'غير موجود.'});if(!['GET','POST','PATCH','DELETE'].includes(method))return reply(405,{error:'طريقة غير متاحة.'});
 async function rest(table,params={},options={}){const q=new URLSearchParams(params);const r=await fetchImpl(url+'/rest/v1/'+table+(q.size?'?'+q:''),{...options,headers:{apikey:secret,Authorization:'Bearer '+secret,'Content-Type':'application/json',...options.headers}});if(!r.ok)throw new Error('Database request failed: '+r.status);const text=await r.text();return {rows:text?JSON.parse(text):null,count:Number(r.headers.get('content-range')?.split('/')[1])||0};}
 async function member(){const token=String(req.headers.authorization||'');if(!/^Bearer \S+$/i.test(token))throw new ClientError('سجل الدخول أولًا.',401);const r=await fetchImpl(url+'/auth/v1/user',{headers:{apikey:publicKey,Authorization:token}});if(!r.ok)throw new ClientError('جلسة الدخول انتهت. سجل الدخول مرة أخرى.',401);const u=await r.json();if(!u.id||!u.email||!u.email_confirmed_at)throw new ClientError('غير مصرح بالدخول.',403);const email=u.email.toLowerCase();if(email===owner)return {email,owner:true};const {rows}=await rest('move_now_admins',{email:'eq.'+email,select:'email',limit:'1'});if(!rows.length)throw new ClientError('غير مصرح بالدخول.',403);return {email,owner:false};}
 if(method!=='GET')requireOrigin(req);
 if(resource==='leads'&&method==='POST'){const lead=validateLead(bodyOf(req,16000));const {rows:existing}=await rest('move_now_leads',{id:'eq.'+lead.id,select:'id',limit:'1'});if(existing.length)return reply(200,{id:lead.id});const ip=String(req.headers['x-vercel-forwarded-for']||req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();const key=createHash('sha256').update(ip+new Date().toISOString().slice(0,10)).digest('hex');const {rows:rate}=await rest('rpc/move_now_submission_attempt',{}, {method:'POST',body:JSON.stringify({p_key:key,p_window:Math.floor(Date.now()/3600000)})});if(rate>10)throw new ClientError('وصلت للحد المسموح من الطلبات. حاول لاحقًا.',429);await rest('move_now_leads',{}, {method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify(lead)});return reply(201,{id:lead.id});}
 const user=await member();if(resource==='session'&&method==='GET')return reply(200,user);
 if(resource==='leads'&&method==='GET'){const q=String(queryValue(req,'q')).slice(0,100).replace(/[(),.*"\\]/g,' ').trim();const status=String(queryValue(req,'status'));const service=String(queryValue(req,'service'));const page=Math.floor(Math.max(0,Math.min(100000,Number(queryValue(req,'page'))||0)));const params={select:'*',order:'created_at.desc',limit:'50',offset:String(page*50)};if(q)params.or=`(name.ilike.*${q}*,phone.ilike.*${q}*,details.ilike.*${q}*)`;if(status){if(!statuses.includes(status))throw new ClientError('حالة غير صحيحة.');params.status='eq.'+status;}if(service){if(!services.includes(service))throw new ClientError('خدمة غير صحيحة.');params.service='eq.'+service;}
 const [list,stats]=await Promise.all([rest('move_now_leads',params,{headers:{Prefer:'count=exact'}}),rest('rpc/move_now_stats',{}, {method:'POST',body:'{}'})]);return reply(200,{leads:list.rows,total:list.count,stats:stats.rows,user:user.email,owner:user.owner});}
 if(resource==='leads'&&method==='PATCH'){const p=bodyOf(req,16000);if(!uuid(p.id)||!statuses.includes(p.status)||typeof p.assigned!=='string'||p.assigned.length>254||typeof p.notes!=='string'||p.notes.length>10000||typeof p.nextFollowup!=='string'||(p.nextFollowup&&!/^\d{4}-\d{2}-\d{2}$/.test(p.nextFollowup))||!Number.isSafeInteger(p.updatedAt))throw new ClientError('راجع بيانات المتابعة.');
 if(p.assigned&&p.assigned!==owner){const {rows}=await rest('move_now_admins',{email:'eq.'+p.assigned,select:'email',limit:'1'});if(!rows.length)throw new ClientError('اختر مسؤولًا من الفريق.');}const updatedAt=Date.now();const {rows}=await rest('move_now_leads',{id:'eq.'+p.id,updated_at:'eq.'+p.updatedAt},{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:p.status,assigned:p.assigned,notes:p.notes,next_followup:p.nextFollowup,updated_at:updatedAt})});if(!rows.length)throw new ClientError('الطلب اتعدّل بواسطة أحد أفراد الفريق. حدّث الصفحة قبل الحفظ.',409);return reply(200,{updatedAt});}
 if(resource==='admins'&&method==='GET'){const {rows}=await rest('move_now_admins',{select:'email,name',order:'created_at.asc'});return reply(200,{admins:[{email:owner,name:'مالك الحساب'},...rows.filter(r=>r.email!==owner)]});}
 if(resource==='admins'&&['POST','DELETE'].includes(method)){if(!user.owner)throw new ClientError('إدارة الفريق متاحة لمالك الحساب فقط.',403);const p=bodyOf(req,2000);const email=typeof p.email==='string'?p.email.trim().toLowerCase():'';if(email.length>254||!/^\S+@[^\s@]+\.[^\s@]+$/.test(email))throw new ClientError('اكتب بريدًا صحيحًا.');if(email===owner)throw new ClientError('هذا الحساب هو مالك اللوحة بالفعل.');if(method==='POST'){const name=typeof p.name==='string'?p.name.trim():'';if(name.length<2||name.length>100)throw new ClientError('اكتب اسمًا صحيحًا.');await rest('move_now_admins',{}, {method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({email,name,created_at:Date.now()})});}else await rest('move_now_admins',{email:'eq.'+email},{method:'DELETE'});return reply(200,{ok:true});}
 return reply(405,{error:'طريقة غير متاحة.'});
 }catch(e){if(!(e instanceof ClientError))console.error('Move Now request failed',{resource:req.query?.resource,method:req.method});return reply(e instanceof ClientError?e.status:503,{error:e instanceof ClientError?e.message:'تعذر تنفيذ الطلب. حاول مرة أخرى.'});}
 };}
module.exports={createHandler,validateLead};
