(() => {
  const init=()=>{
    const form=document.getElementById('project-form');
    const cfg=window.PORTFOLIO_CONFIG;
    if(!form||!cfg||document.getElementById('arabic-project-fields'))return;
    const grid=form.querySelector('.form-grid');
    const wrap=document.createElement('section');
    wrap.id='arabic-project-fields';wrap.className='arabic-project-fields wide';wrap.dir='rtl';
    wrap.innerHTML=`<div class="arabic-fields-head"><div><strong>النسخة العربية للمشروع</strong><span>تظهر تلقائيًا للزائر عند اختيار «عربي» في الموقع.</span></div><b>AR</b></div><div class="arabic-fields-grid"><label class="wide">عنوان المشروع بالعربية<input name="title_ar"></label><label class="wide">الوصف المختصر بالعربية<textarea name="excerpt_ar" rows="3"></textarea></label><label class="wide">الوصف الكامل بالعربية<textarea name="description_ar" rows="5"></textarea></label><label>التحدي بالعربية<textarea name="challenge_ar" rows="5"></textarea></label><label>الحل بالعربية<textarea name="solution_ar" rows="5"></textarea></label><label class="wide">النتيجة / الأثر بالعربية<textarea name="result_ar" rows="4"></textarea></label><label class="wide">الكلمات المفتاحية بالعربية<input name="tags_ar" placeholder="سلامة، ذكاء اصطناعي، تصميم"></label><label class="wide">الأدوات بالعربية<input name="tools_ar" placeholder="تقييم مخاطر، تطوير ويب، تصميم"></label></div>`;
    grid.appendChild(wrap);
    const style=document.createElement('style');style.textContent=`.arabic-project-fields{grid-column:1/-1;margin:10px 0 6px;padding:18px;border:1px solid rgba(71,148,198,.28);border-radius:16px;background:linear-gradient(135deg,rgba(18,61,88,.34),rgba(7,25,35,.78));font-family:Tahoma,Arial,sans-serif}.arabic-fields-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:14px}.arabic-fields-head strong{display:block;color:#fff;font-size:14px}.arabic-fields-head span{display:block;color:#85a2b3;font-size:10px;line-height:1.7;margin-top:4px}.arabic-fields-head b{background:#1d78a7;color:#fff;padding:7px 9px;border-radius:999px;font:900 9px Montserrat,Arial,sans-serif}.arabic-fields-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.arabic-fields-grid .wide{grid-column:1/-1}.arabic-project-fields input,.arabic-project-fields textarea{text-align:right;direction:rtl;font-family:Tahoma,Arial,sans-serif}@media(max-width:760px){.arabic-fields-grid{grid-template-columns:1fr}.arabic-fields-grid .wide{grid-column:auto}}`;document.head.appendChild(style);

    const DEVICE_KEY='andrew_portfolio_device_v2';let device=null;try{device=JSON.parse(localStorage.getItem(DEVICE_KEY)||'null')}catch(_e){}
    const sb=device?.id&&device?.secret?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey,{global:{headers:{'x-portfolio-device-id':device.id,'x-portfolio-device-secret':device.secret}},auth:{persistSession:false}}):null;
    const fields=['title_ar','excerpt_ar','description_ar','challenge_ar','solution_ar','result_ar','tags_ar','tools_ar'];
    const fill=async()=>{if(!sb)return;const id=form.elements.id?.value;if(!id){fields.forEach(k=>{if(form.elements[k])form.elements[k].value=''});return}const {data}=await sb.from('portfolio_projects').select(fields.join(',')).eq('id',id).maybeSingle();if(!data)return;fields.forEach(k=>{if(!form.elements[k])return;form.elements[k].value=Array.isArray(data[k])?data[k].join(', '):(data[k]||'')})};
    document.addEventListener('click',e=>{if(e.target.closest('[data-open-project],#add-project,#quick-add'))setTimeout(fill,80)});
    const dialog=document.getElementById('project-dialog');new MutationObserver(()=>{if(dialog?.open)setTimeout(fill,60)}).observe(dialog,{attributes:true,attributeFilter:['open']});
    form.addEventListener('submit',()=>{if(!sb)return;const slug=form.elements.slug?.value?.trim();if(!slug)return;const split=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);const payload={title_ar:form.elements.title_ar?.value||'',excerpt_ar:form.elements.excerpt_ar?.value||'',description_ar:form.elements.description_ar?.value||'',challenge_ar:form.elements.challenge_ar?.value||'',solution_ar:form.elements.solution_ar?.value||'',result_ar:form.elements.result_ar?.value||'',tags_ar:split(form.elements.tags_ar?.value),tools_ar:split(form.elements.tools_ar?.value)};let tries=0;const save=async()=>{tries++;const {data}=await sb.from('portfolio_projects').select('id').eq('slug',slug).maybeSingle();if(data?.id){await sb.from('portfolio_projects').update(payload).eq('id',data.id);return}if(tries<5)setTimeout(save,400)};setTimeout(save,300)});
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();