(()=>{
  const cfg=window.PORTFOLIO_CONFIG;if(!cfg||!window.supabase)return;
  const DEVICE_KEY='andrew_portfolio_device_v2';let device=null;try{device=JSON.parse(localStorage.getItem(DEVICE_KEY)||'null')}catch(_e){}if(!device?.id||!device?.secret)return;
  const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey,{global:{headers:{'x-portfolio-device-id':device.id,'x-portfolio-device-secret':device.secret}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  const nav=document.getElementById('admin-nav'),main=document.querySelector('.admin-main');if(!nav||!main)return;
  const btn=document.createElement('button');btn.dataset.tab='text';btn.innerHTML='Aa <span>All Site Text</span>';nav.insertBefore(btn,nav.querySelector('[data-tab="media"]'));
  const panel=document.createElement('section');panel.className='tab-panel';panel.dataset.panel='text';panel.innerHTML=`<div class="panel-card text-cms-shell"><div class="panel-head"><div><span>FULL TEXT CMS</span><h2>Every editable word</h2><p class="text-cms-intro">Edit the fixed website copy here in English and Arabic. Project titles, descriptions, challenge, solution and impact remain editable inside each project. Media titles and briefs remain inside the media editor.</p></div><div class="text-cms-top-actions"><button type="button" class="secondary" id="text-cms-reload">RELOAD</button><button type="button" class="primary" id="text-cms-save-all">SAVE ALL CHANGES</button></div></div><div class="text-cms-toolbar"><input id="text-cms-search" placeholder="Search text, section or key..."><select id="text-cms-scope"><option value="all">All pages</option></select><select id="text-cms-section"><option value="all">All sections</option></select></div><div id="text-cms-status" class="text-cms-status">Open this tab to load site text.</div><div id="text-cms-list" class="text-cms-list"></div></div>`;main.appendChild(panel);
  const style=document.createElement('style');style.textContent=`
    .text-cms-shell{padding-bottom:26px}.text-cms-intro{max-width:720px;color:#78909d;font-size:9px;line-height:1.7;margin:7px 0 0}.text-cms-top-actions{display:flex;gap:8px;flex-wrap:wrap}.text-cms-toolbar{display:grid;grid-template-columns:minmax(260px,1fr) 190px 190px;gap:9px;margin:18px 0}.text-cms-toolbar input,.text-cms-toolbar select{width:100%;border:1px solid rgba(255,255,255,.1);background:#071924;color:#fff;border-radius:10px;padding:11px 12px;font:700 9px Montserrat,Arial,sans-serif}.text-cms-status{font-size:8px;color:#79909c;margin:4px 0 12px}.text-cms-list{display:grid;gap:10px}.text-cms-card{border:1px solid rgba(255,255,255,.08);border-radius:14px;background:#06141e;padding:13px}.text-cms-card.dirty{border-color:rgba(225,6,19,.65);box-shadow:0 0 0 1px rgba(225,6,19,.08)}.text-cms-card-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:10px}.text-cms-card-head strong{display:block;font-size:10px;color:#fff}.text-cms-card-head small{display:block;margin-top:4px;color:#68818e;font-size:7px}.text-cms-badges{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.text-cms-badges span{padding:5px 7px;border-radius:999px;background:#0b2a3d;color:#8fa5b1;font-size:7px;font-weight:800}.text-cms-fields{display:grid;grid-template-columns:1fr 1fr;gap:9px}.text-cms-fields label{color:#8399a5;font-size:8px}.text-cms-fields textarea{display:block;width:100%;min-height:74px;margin-top:5px;padding:10px;border:1px solid rgba(255,255,255,.09);border-radius:9px;background:#091f2d;color:#fff;resize:vertical;font:500 9px/1.65 Montserrat,Arial,sans-serif}.text-cms-fields textarea[dir="rtl"]{font-family:Arial,Tahoma,sans-serif;text-align:right;line-height:1.9}.text-cms-card-actions{display:flex;justify-content:flex-end;margin-top:9px}.text-cms-save{border:0;border-radius:8px;background:#0c3046;color:#fff;padding:8px 10px;font:900 7px Montserrat,Arial,sans-serif;cursor:pointer}.text-cms-card.dirty .text-cms-save{background:#e10613}.text-cms-empty{padding:30px;text-align:center;color:#718794;border:1px dashed rgba(255,255,255,.1);border-radius:12px}
    @media(max-width:800px){.text-cms-toolbar{grid-template-columns:1fr}.text-cms-fields{grid-template-columns:1fr}.text-cms-card-head{flex-direction:column}.text-cms-badges{justify-content:flex-start}.text-cms-top-actions{width:100%}.text-cms-top-actions button{flex:1}}
  `;document.head.appendChild(style);
  let rows=[],loaded=false;
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=s=>panel.querySelector(s);
  function showTab(){document.querySelectorAll('#admin-nav button').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p===panel));const t=document.getElementById('page-title');if(t)t.textContent='All Site Text';if(!loaded)load()}
  btn.addEventListener('click',showTab);
  function refreshFilters(){const scope=$('#text-cms-scope'),section=$('#text-cms-section'),sv=scope.value||'all',secv=section.value||'all';const scopes=[...new Set(rows.map(r=>r.scope))].sort(),sections=[...new Set(rows.map(r=>r.section))].sort();scope.innerHTML='<option value="all">All pages</option>'+scopes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');section.innerHTML='<option value="all">All sections</option>'+sections.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(scopes.includes(sv))scope.value=sv;if(sections.includes(secv))section.value=secv}
  function filtered(){const q=$('#text-cms-search').value.trim().toLowerCase(),scope=$('#text-cms-scope').value,section=$('#text-cms-section').value;return rows.filter(r=>(scope==='all'||r.scope===scope)&&(section==='all'||r.section===section)&&(!q||[r.label,r.content_key,r.section,r.scope,r.value_en,r.value_ar].join(' ').toLowerCase().includes(q)))}
  function card(r){return `<article class="text-cms-card" data-text-id="${r.id}"><div class="text-cms-card-head"><div><strong>${esc(r.label)}</strong><small>${esc(r.content_key)}</small></div><div class="text-cms-badges"><span>${esc(r.scope)}</span><span>${esc(r.section)}</span><span>${esc(r.mode)}</span></div></div><div class="text-cms-fields"><label>English<textarea name="value_en">${esc(r.value_en||'')}</textarea></label><label>العربي<textarea name="value_ar" dir="rtl">${esc(r.value_ar||'')}</textarea></label></div><div class="text-cms-card-actions"><button type="button" class="text-cms-save">SAVE</button></div></article>`}
  function render(){const list=$('#text-cms-list'),data=filtered();list.innerHTML=data.length?data.map(card).join(''):'<div class="text-cms-empty">No text items match this filter.</div>';$('#text-cms-status').textContent=`${data.length} of ${rows.length} text items shown`;list.querySelectorAll('textarea').forEach(el=>el.addEventListener('input',()=>el.closest('.text-cms-card').classList.add('dirty')));list.querySelectorAll('.text-cms-save').forEach(b=>b.addEventListener('click',()=>saveCard(b.closest('.text-cms-card'))))}
  async function load(){loaded=true;$('#text-cms-status').textContent='Loading site text…';const {data,error}=await sb.from('portfolio_text_content').select('*').order('sort_order',{ascending:true});if(error){$('#text-cms-status').textContent=error.message;return}rows=data||[];refreshFilters();render()}
  async function saveCard(card){const id=card.dataset.textId,row=rows.find(r=>r.id===id);if(!row)return;const b=card.querySelector('.text-cms-save');b.disabled=true;b.textContent='SAVING…';const value_en=card.querySelector('[name="value_en"]').value,value_ar=card.querySelector('[name="value_ar"]').value;const {error}=await sb.from('portfolio_text_content').update({value_en,value_ar,updated_at:new Date().toISOString()}).eq('id',id);b.disabled=false;if(error){b.textContent='ERROR';return}row.value_en=value_en;row.value_ar=value_ar;card.classList.remove('dirty');b.textContent='SAVED ✓';setTimeout(()=>b.textContent='SAVE',1000)}
  async function saveAll(){const dirty=[...panel.querySelectorAll('.text-cms-card.dirty')];const b=$('#text-cms-save-all');if(!dirty.length){b.textContent='NOTHING TO SAVE';setTimeout(()=>b.textContent='SAVE ALL CHANGES',1000);return}b.disabled=true;b.textContent=`SAVING ${dirty.length}…`;for(const c of dirty)await saveCard(c);b.disabled=false;b.textContent='ALL SAVED ✓';setTimeout(()=>b.textContent='SAVE ALL CHANGES',1200)}
  $('#text-cms-search').addEventListener('input',render);$('#text-cms-scope').addEventListener('change',render);$('#text-cms-section').addEventListener('change',render);$('#text-cms-reload').addEventListener('click',load);$('#text-cms-save-all').addEventListener('click',saveAll);
})();