import {useEffect,useRef,useState} from 'react';
import {Compass,PhoneCall,NotebookPen,Sparkles,ArrowUpRight,Save,Plus,History,Copy,Check,Pause,Play,X} from 'lucide-react';
import Brand from './brand';import {apiFetch,signOut} from './transport';import type {Lead} from './model';
import {fields as definitions,choices as callChoices,emptyCRM,view,cleanCRM} from '../../server/move-now-call-model.cjs';

type CRM=Record<string,string>;
type Result={crm:CRM;uncertain:string[];nudge:string;recap:string;model?:string;id?:string;locked?:string[]};
type Call={id:string;lead_id:string|null;agent_email:string;raw_notes:string;crm:CRM;analysis:Result;stage:'draft'|'completed';updated_at:number;created_at:number;locked?:string[]};
const fields=definitions as unknown as [string,string,string[]?][];
const choices=callChoices as Record<string,Record<string,string>>;
const icons={complete:'✅',partial:'🟡',empty:'⚪'};
function fresh(email:string):Call{return {id:crypto.randomUUID(),lead_id:null,agent_email:email,raw_notes:'',crm:emptyCRM(),analysis:null,stage:'draft',updated_at:0,created_at:Date.now()};}
function date(value:number){return new Date(value).toLocaleString('ar-EG',{dateStyle:'short',timeStyle:'short',timeZone:'Africa/Cairo'});}
function leadCRM(lead:Lead):CRM{const d=JSON.parse(lead.details);return {...emptyCRM(),clientName:lead.name,phone:lead.phone,service:['buy','both'].includes(lead.service)?'':lead.service,route:lead.service.startsWith('buy')?'buy':lead.service==='sell'?'sale':lead.service.includes('rent')?'rent':'finish',financialClass:lead.service==='buy_installments'?'installments':lead.service==='buy_cash'?'cash':'',location:d.location||'',propertyType:d.type||'',area:d.area||'',rooms:d.rooms||'',condition:d.condition||'',budget:d.budget||'',downPayment:d.downPayment||'',monthlyInstallment:d.monthlyInstallment||'',installmentYears:d.installmentYears||'',finishLevel:d.finishLevel||'',furnitureScope:d.furnitureScope||'',rentType:d.rentType||'',delivery:d.delivery||'',timing:d.timeline||'',nextStep:d.nextStep||'',followupTime:lead.next_followup||d.followupTime||''};}
export default function CallCenter({email}:{email:string;owner:boolean}){
 const [call,setCall]=useState<Call>(()=>{try{const saved=JSON.parse(sessionStorage.getItem('move-now-call:'+email)||'null');if(saved?.id&&typeof saved.raw_notes==='string'&&saved.stage==='draft')return {...saved,crm:cleanCRM(saved.crm)};}catch{}return fresh(email)});
 const [notes,setNotes]=useState(call.raw_notes);const [crm,setCRM]=useState<CRM>(call.crm);const [result,setResult]=useState<Result|null>(call.analysis);
 const [locked,setLocked]=useState<string[]>(call.locked||call.analysis?.locked||[]);const [enabled,setEnabled]=useState(true);const [run,setRun]=useState(0);const [analysisState,setAnalysisState]=useState('idle');const [analysisError,setAnalysisError]=useState('');
 const [busy,setBusy]=useState(false);const [saved,setSaved]=useState('');const [error,setError]=useState('');const [history,setHistory]=useState<Call[]|null>(null);const [historyBusy,setHistoryBusy]=useState(false);const [copied,setCopied]=useState('');
 const sequence=useRef(0);const latest=useRef({crm,locked});latest.current={crm,locked};const historyDialog=useRef<HTMLElement>(null);
 const completed=call.stage==='completed';const uncertain=result?.uncertain||[];const visual=view(crm,uncertain);const current=result&&JSON.stringify(result.crm)===JSON.stringify(crm);
 const nudge=current?result.nudge:visual.nudge;const recap=current?result.recap:visual.recap;
 const status=analysisState==='waiting'?'في انتظار توقف الكتابة…':analysisState==='running'?'جاري تحليل الملاحظات…':analysisState==='ready'?'تم تحديث التحليل':analysisState==='error'?'التحليل متوقف — الحقول متاحة يدويًا':enabled?'جاهز للملاحظات':'التحليل موقوف';
 useEffect(()=>{if(completed){sessionStorage.removeItem('move-now-call:'+email);return;}try{sessionStorage.setItem('move-now-call:'+email,JSON.stringify({...call,raw_notes:notes,crm,analysis:result,locked}));}catch{}},[call,notes,crm,result,locked,email,completed]);
 useEffect(()=>{const leadId=new URLSearchParams(window.location.search).get('leadId');const callId=new URLSearchParams(window.location.search).get('call');if(!leadId&&!callId)return;let cancelled=false;
  (async()=>{try{const r=await apiFetch('/api/calls?'+new URLSearchParams(callId?{id:callId}:{leadId}));const data=await r.json();if(!r.ok)throw Error(data.error);if(cancelled)return;const loaded:Call=callId?data.calls[0]:{...fresh(email),lead_id:data.lead.id,crm:leadCRM(data.lead)};if(!loaded)throw Error('المكالمة غير موجودة.');setCall(loaded);setCRM(loaded.crm);setNotes(loaded.raw_notes);setResult(loaded.analysis||null);setLocked(loaded.analysis?.locked||[]);}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'تعذر فتح الطلب.');}})();return()=>{cancelled=true};
 },[email]);
 useEffect(()=>{const seq=++sequence.current;const controller=new AbortController();if(!enabled||completed||!notes.trim()){setAnalysisState('idle');return()=>controller.abort();}setAnalysisState('waiting');setAnalysisError('');
  const timer=window.setTimeout(async()=>{setAnalysisState('running');try{const snapshot=latest.current;const r=await apiFetch('/api/copilot',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({callId:call.id,notes,previous:snapshot.crm,locked:snapshot.locked})});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر التحليل.');if(seq!==sequence.current)return;setCRM(d.crm);setResult(d);setAnalysisState('ready');}catch(e){if(controller.signal.aborted||seq!==sequence.current)return;setAnalysisState('error');setAnalysisError(e instanceof Error?e.message:'تعذر التحليل الذكي.');}},1100);
  return()=>{clearTimeout(timer);controller.abort()};
 },[notes,enabled,run,call.id,completed]);
 useEffect(()=>{if(!history)return;const prior=document.activeElement as HTMLElement;const dialog=historyDialog.current;const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button,a[href],input,select,[tabindex="0"]')||[]);focusable()[0]?.focus();const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'){setHistory(null);return;}if(e.key==='Tab'){const items=focusable(),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};dialog?.addEventListener('keydown',keydown);return()=>{dialog?.removeEventListener('keydown',keydown);prior?.focus();};},[history]);
 function edit(key:string,value:string){sequence.current++;setAnalysisState('idle');setSaved('');setCRM(previous=>({...previous,[key]:value}));setLocked(previous=>previous.includes(key)?previous:[...previous,key]);setResult(previous=>previous?{...previous,uncertain:previous.uncertain.filter(k=>k!==key)}:null);}
 async function save(publish:boolean){if(!notes.trim()&&!crm.clientName){setError('اكتب ملاحظات أو اسم العميل الأول.');return;}setBusy(true);setSaved('');setError('');try{const r=await apiFetch('/api/calls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:call.id,leadId:call.lead_id,notes,crm,uncertain,locked,publish,updatedAt:call.updated_at})});const d=await r.json();if(!r.ok)throw Error(d.error);setCall(d.call);setSaved(publish?'اتحفظت المكالمة واتسجلت المتابعة في الداشبورد.':'تم حفظ مسودة المكالمة.');}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ المكالمة.');}finally{setBusy(false)}}
 function newCall(){if(!completed&&(notes.trim()||crm.clientName)&&!window.confirm('بدء مكالمة جديدة؟ احفظ المسودة الحالية أولًا لو محتاج ترجع لها.'))return;sequence.current++;setCall(fresh(email));setNotes('');setCRM(emptyCRM());setResult(null);setLocked([]);setSaved('');setError('');setAnalysisError('');setEnabled(true);setHistory(null);window.history.replaceState(null,'','/move-now/call-center');}
 async function loadHistory(){setHistoryBusy(true);setError('');try{const r=await apiFetch('/api/calls');const d=await r.json();if(!r.ok)throw Error(d.error);setHistory(d.calls);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المكالمات.');}finally{setHistoryBusy(false)}}
 function openCall(item:Call){if(!completed&&(notes.trim()||crm.clientName)&&!window.confirm('فتح مكالمة محفوظة؟ احفظ المسودة الحالية أولًا لو محتاج ترجع لها.'))return;sequence.current++;setCall(item);setCRM(item.crm);setNotes(item.raw_notes);setResult(item.analysis);setLocked(item.analysis?.locked||[]);setSaved('');setError('');setHistory(null);window.history.replaceState(null,'','/move-now/call-center?call='+item.id);}
 async function copy(text:string,kind:string){try{await navigator.clipboard.writeText(text);setCopied(kind);window.setTimeout(()=>setCopied(''),2000);}catch{setError('تعذر النسخ. تقدر تحدد النص وتنسخه يدويًا.');}}
 return <><header className="topbar"><Brand/><span className="header-tag">مساحة موظف الكول سنتر</span><div className="header-links"><a className="staff-link" href="/move-now/admin">الطلبات والمتابعة</a><button className="staff-link" onClick={signOut}>خروج</button></div></header>
 <main className="call-workspace"><div className="call-heading"><div><span className="eyebrow">اسمع العميل. خلّي التفاصيل قدامك.</span><h1>مساعد المكالمة</h1><p>اكتب بطريقتك، راجع البيانات، وثبّت الخطوة الجاية.</p></div><div className="call-agent"><span>الموظف المسؤول</span><strong dir="ltr">{email}</strong><small>{completed?'مكالمة محفوظة':'مكالمة جارية'} · MN-{call.id.slice(0,8).toUpperCase()}</small></div></div>
 <div className="call-toolbar"><div><button className="secondary" disabled={busy} onClick={newCall}><Plus size={17}/>مكالمة جديدة</button><button className="secondary" disabled={historyBusy} onClick={loadHistory}><History size={17}/>{historyBusy?'جاري التحميل…':'سجل مكالماتي'}</button></div><span className={'analysis-status '+analysisState} role="status"><span/>{status}</span></div>
 {error&&<p role="alert" className="error call-notice">{error}</p>}{saved&&<p role="status" className="saved call-notice">{saved}</p>}
 <div className="call-layout"><aside className="scratch-panel"><div className="section-title"><NotebookPen size={20}/><div><h2>ملاحظات المكالمة</h2><p>شخبطة سريعة، عربي أو فرانكو.</p></div></div><div className="call-hook"><span>افتتاحية مقترحة</span><p>إحنا Move Now، بنقدّم دراسة مجانية لتعظيم العائد من عقارك وتقييم سعره الحالي في السوق، من غير أي التزام. ينفع أعرف حضرتك محتاج تستفيد من العقار إزاي؟</p></div><label htmlFor="call-notes">اكتب اللي العميل بيقوله</label><textarea id="call-notes" aria-label="شخبطة المكالمة" disabled={completed||busy} maxLength={12000} value={notes} onChange={e=>{sequence.current++;setNotes(e.target.value);setSaved('')}} placeholder="مثال: م أحمد، زايد، عايز يشتري قسط. مقدم نص مليون، 15 ألف شهري. استلام سنة. 010…"/><small className="notes-foot">{notes.length.toLocaleString('ar-EG')} / ١٢٬٠٠٠ · المسودة محفوظة في الجلسة الحالية.</small><div className="scratch-actions"><button className="secondary small" disabled={completed} onClick={()=>setEnabled(!enabled)}>{enabled?<Pause size={16}/>:<Play size={16}/>}{enabled?'إيقاف التحليل':'تشغيل التحليل'}</button><button className="secondary small" disabled={completed||!notes.trim()||analysisState==='running'} onClick={()=>{setEnabled(true);setRun(run+1)}}><Sparkles size={16}/>تحديث التحليل</button></div>{analysisError&&<p role="alert" className="error">{analysisError}</p>}
 <div className="call-save"><button className="secondary full" disabled={busy||completed} onClick={()=>save(false)}><Save size={17}/>{busy?'جاري الحفظ…':'حفظ المسودة'}</button><button className="primary full" disabled={busy||completed||analysisState==='running'||analysisState==='waiting'} onClick={()=>save(true)}><Check size={18}/>حفظ الطلب والمتابعة</button><small>راجع الحقول قبل الحفظ. الطلب يُسند لحساب الموظف، والتواصل الفعلي يتم بواسطة الفريق.</small>{call.lead_id&&<a href="/move-now/admin">فتح الطلبات في الداشبورد <ArrowUpRight size={15}/></a>}</div></aside>
 <div className="copilot-output"><section className="call-card compass-card"><div className="section-title"><Compass size={21}/><div><span className="section-number">01</span><h2>بوصلة المكالمة</h2></div><small>✅ مكتمل · 🟡 يحتاج تأكيد · ⚪ لم يُذكر</small></div><div className="call-compass">{visual.compass.map(station=><div className={'compass-station '+station.status} key={station.key}><span>{icons[station.status]}</span><strong>{station.label}</strong><small>{station.status==='complete'?'محدد':station.status==='partial'?'كمّل / أكّد':'لم يُذكر'}</small></div>)}</div></section>
 <section className="call-card nudge-card"><div className="section-title"><Sparkles size={20}/><div><span className="section-number">02</span><h2>السؤال التالي</h2></div></div><p className="live-nudge" aria-live="polite">{nudge}</p></section>
 <section className="call-card crm-card"><div className="section-title"><PhoneCall size={20}/><div><span className="section-number">03</span><h2>بيانات العميل والطلب</h2></div><small>التعديل اليدوي يحافظ على اختيارك.</small></div><div className="call-fields">{fields.map(([key,label,options])=><label className={'field '+(uncertain.includes(key)?'needs-confirmation':'')} key={key}><span>{label}{uncertain.includes(key)&&<em>يحتاج تأكيد</em>}{locked.includes(key)&&<small>تعديل الموظف</small>}</span>{options?<select disabled={completed||busy} aria-label={label} value={crm[key]} onChange={e=>edit(key,e.target.value)}>{options.map(option=><option key={option} value={option}>{choices[key]?.[option]||option}</option>)}</select>:<input disabled={completed||busy} aria-label={label} value={crm[key]} maxLength={600} inputMode={key==='phone'?'tel':['area','rooms','downPayment','monthlyInstallment','installmentYears'].includes(key)?'decimal':'text'} onChange={e=>edit(key,e.target.value)} placeholder="لم يُذكر بعد"/>}</label>)}</div><div className="missing-data"><strong>البيانات الناقصة الحرجة</strong>{visual.missing.length?<div>{visual.missing.map(item=><span key={item}>{item}</span>)}</div>:<p>المحطات الأساسية مكتملة. راجع الدقة مع العميل قبل الحفظ.</p>}</div></section>
 <section className="call-card recap-card"><div className="section-title"><Check size={20}/><div><span className="section-number">04</span><h2>القفلة والتلخيص</h2></div><button className="secondary small" onClick={()=>copy(recap,'recap')}>{copied==='recap'?<Check size={16}/>:<Copy size={16}/>}{copied==='recap'?'تم النسخ':'نسخ القفلة'}</button></div><p>{recap}</p></section></div></div>
 </main>{history&&<div className="overlay"><section ref={historyDialog} className="call-history" role="dialog" aria-modal="true" aria-labelledby="call-history-title"><div className="dialog-head"><h2 id="call-history-title">سجل مكالماتي</h2><button className="icon-btn" aria-label="إغلاق سجل المكالمات" onClick={()=>setHistory(null)}><X/></button></div>{history.length?<ul>{history.map(item=><li key={item.id}><div><strong>{item.crm.clientName||'مكالمة بدون اسم'}</strong><small>{choices.service[item.crm.service]||'الخدمة لم تُحدد'} · {date(item.created_at)}</small><small>{item.stage==='draft'?'مسودة':'محفوظة في الداشبورد'} · {item.agent_email}</small></div><button className="secondary small" onClick={()=>openCall(item)}>فتح المكالمة</button></li>)}</ul>:<p>لسه مفيش مكالمات محفوظة لحسابك.</p>}</section></div>}</>;
}
