import {useEffect,useState} from 'react';import {createRoot} from 'react-dom/client';import Page from './page';import Dashboard from './dashboard';import Brand from './brand';import {apiFetch,authClient,signOut} from './transport';
function Admin(){const [user,setUser]=useState<{email:string;owner:boolean}|null>(null);const [loading,setLoading]=useState(true);const [email,setEmail]=useState('');const [code,setCode]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [denied,setDenied]=useState(false);const otpLength=(window as any).ATS_AUTH?.otpLength||8;
 async function load(){setLoading(true);setError('');try{const {data,error}=await authClient().auth.getSession();if(error)throw error;if(!data.session){setUser(null);setDenied(false);return;}const r=await apiFetch('/api/session');const d=await r.json();if(r.status===403){setDenied(true);return;}if(!r.ok)throw new Error(d.error||'تعذر تحميل حساب الفريق.');setDenied(false);setUser(d);}catch{setError('تعذر التحقق من الدخول. حاول مرة أخرى.');}finally{setLoading(false);}}
 useEffect(()=>{load();try{const {data}=authClient().auth.onAuthStateChange(()=>{setTimeout(load,0)});return()=>data.subscription.unsubscribe()}catch{return}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const auth=authClient().auth;const result=sent?await auth.verifyOtp({email:email.trim(),token:code,type:'email'}):await auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:window.location.origin+'/move-now/admin'}});if(result.error)throw result.error;if(sent)await load();else setSent(true);}catch{setError(sent?'الكود غير صحيح أو انتهت صلاحيته. حاول مرة أخرى.':'تعذر إرسال كود الدخول. حاول مرة أخرى بعد قليل.');}finally{setBusy(false)}}
 if(user&&!denied)return <Dashboard email={user.email} owner={user.owner}/>;
 return <main className="access-page"><Brand/><span className="eyebrow">لوحة متابعة Move Now</span><h1>{denied?'اللوحة متاحة للفريق فقط':'دخول الفريق'}</h1>{loading?<p role="status">جاري التحقق من الحساب…</p>:denied?<><p>البريد الحالي غير مضاف للفريق. ادخل ببريد مصرح له، أو اطلب من مالك اللوحة إضافته.</p><button className="primary" onClick={signOut}>تغيير الحساب</button></>:<form onSubmit={submit}><label className="field"><span>بريدك الإلكتروني</span><input type="email" dir="ltr" autoComplete="email" required maxLength={254} value={email} disabled={sent||busy} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<label className="field"><span>كود الدخول ({otpLength} أرقام)</span><input dir="ltr" inputMode="numeric" autoComplete="one-time-code" required pattern={'[0-9]{'+otpLength+'}'} minLength={otpLength} maxLength={otpLength} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,otpLength))}/><small>راجع رسالة الدخول في بريدك. لو فيها رابط، افتحه لاستكمال الدخول.</small></label>}<button className="primary full" disabled={busy}>{busy?'جاري التنفيذ…':sent?'دخول اللوحة':'إرسال كود الدخول'}</button>{sent&&<button className="secondary full" style={{marginTop:14}} type="button" disabled={busy} onClick={()=>{setSent(false);setCode('');setError('')}}>تعديل البريد أو إرسال كود جديد</button>}</form>}{error&&<><p className="error" role="alert">{error}</p>{!busy&&<button className="secondary" onClick={load}>إعادة المحاولة</button>}</>}<a href="/move-now">العودة لصفحة الطلبات</a></main>;
}
createRoot(document.getElementById('root')!).render(window.location.pathname.replace(/\/$/,'')==='/move-now/admin'?<Admin/>:<Page/>);
