insert into public.studio_knowledge_sources
(source_key,domain,title,publisher,source_type,authority_tier,url,version_label,jurisdiction,principles,status,verified_at,notes)
values
('nist_ai_rmf_1_0','ai_systems','NIST Artificial Intelligence Risk Management Framework (AI RMF) 1.0','National Institute of Standards and Technology','government',1,'https://www.nist.gov/itl/ai-risk-management-framework','1.0','US / global reference','["Manage AI risks across governance, mapping, measurement, and management activities.","Treat trustworthiness as context-dependent and evaluate risks throughout the AI lifecycle.","Use evidence, documented assumptions, monitoring, and human accountability rather than treating model output as inherently reliable."]'::jsonb,'active',now(),'AI RMF 1.0 is a voluntary cross-sector framework; NIST notes that a revision is in progress.'),
('nist_ai_600_1','ai_systems','NIST AI 600-1 — Generative Artificial Intelligence Profile','National Institute of Standards and Technology','government',1,'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence','600-1','US / global reference','["Identify and manage risks that are specific or amplified by generative AI.","Evaluate outputs, misuse pathways, data and privacy concerns, human-AI configuration, and downstream impacts in the actual use context.","Use testing, monitoring, documentation, and human oversight proportionate to risk."]'::jsonb,'active',now(),'Published July 2024 as a companion resource to AI RMF 1.0.'),
('iso_24495_1_2023','content','ISO 24495-1:2023 — Plain language — Part 1: Governing principles and guidelines','International Organization for Standardization','standard',1,'https://www.iso.org/standard/78907.html','2023','global','["Create text so intended readers can find what they need, understand what they find, and use that information.","Design written information around the audience, purpose, structure, wording, and usability rather than writer preference.","Apply plain-language principles to digital and printed text while using separate accessibility guidance where needed."]'::jsonb,'active',now(),'Published International Standard for written information; use WCAG separately for digital accessibility.'),
('iso_20671_1_2021','brand','ISO 20671-1:2021 — Brand evaluation — Part 1: Principles and fundamentals','International Organization for Standardization','standard',1,'https://www.iso.org/standard/81739.html','2021','global','["Evaluate brands through explicit inputs, output dimensions, and indicators rather than aesthetic opinion alone.","Define the evaluation purpose and relevant stakeholders before selecting indicators.","Use an integrated and documented approach when assessing brand performance and value-related dimensions."]'::jsonb,'active',now(),'Current published replacement for withdrawn ISO 20671:2019.'),
('icc_marketing_code_2024','marketing','ICC Advertising and Marketing Communications Code','International Chamber of Commerce','professional',2,'https://iccwbo.org/business-solutions/the-icc-advertising-and-marketing-communications-code/','2024','global self-regulatory reference','["Marketing communications should be responsible, transparent, and distinguishable as marketing where applicable.","Claims should not mislead and should have an appropriate factual basis, especially for objective or sensitive claims.","Apply responsible marketing principles across digital, social, influencer, AI-assisted, environmental, and child/teen-related communications, subject to applicable local law."]'::jsonb,'active',now(),'Global self-regulatory code; local law and platform rules may impose additional or stricter requirements.')
on conflict (source_key) do update set
 domain=excluded.domain,title=excluded.title,publisher=excluded.publisher,source_type=excluded.source_type,
 authority_tier=excluded.authority_tier,url=excluded.url,version_label=excluded.version_label,
 jurisdiction=excluded.jurisdiction,principles=excluded.principles,status=excluded.status,
 verified_at=excluded.verified_at,notes=excluded.notes,updated_at=now();
